monitor=,preferred,auto,1

input {
    #keyboard
    kb_variant=
    kb_model=
    kb_options=
    kb_rules=
    numlock_by_default=true

    #mouse
    follow_mouse=1
    force_no_accel=true
    sensitivity=0.8 # for mouse cursor
    

    touchpad {
        middle_button_emulation=true
        natural_scroll=yes
    }
}

general {
    main_mod=SUPER

    gaps_in=4
    gaps_out=8
    border_size=2
    col.active_border=0xee2b8492
    col.inactive_border=0xee244348
    no_border_on_floating=true

    apply_sens_to_raw=0 # whether to apply the sensitivity to raw input (e.g. used by games where you aim using your mouse)

    damage_tracking=full # leave it on full unless you hate your GPU and want to make it suffer
}

decoration {
    rounding=10
    blur=1
    blur_size=4 # minimum 1
    blur_passes=2 # minimum 1, more passes = more resource intensive.
    # Your blur "amount" is blur_size * blur_passes, but high blur_size (over around 5-ish) will produce artifacts.
    # if you want heavy blur, you need to up the blur_passes.
    # the more passes, the more you can up the blur_size without noticing artifacts.
    blur_new_optimizations=true
}

animations {
    #animation=NAME,ONOFF,SPEED,CURVE,STYLE
    enabled=1
    #define bezier curves
    bezier=nice, 0.38, 0.5, 0.22, 1
    bezier=bounce, .37,1.5,.41,1.01

    #define animation options
    animation=windows,1,4,nice,popin 80%
    animation=fade,1,10,nice
    animation=border,1,10,nice
    animation=workspaces,1,6,bounce
}

dwindle {
    pseudotile=0 # enable pseudotiling on dwindle
}

gestures {
    workspace_swipe=yes
    workspace_swipe_distance=600
}

# example window rules
# for windows named/classed as abc and xyz
#windowrule=move 69 420,abc
#windowrule=size 420 69,abc
#windowrule=tile,xyz
#windowrule=float,abc
#windowrule=pseudo,abc
#windowrule=monitor 0,xyz

# example binds
bind=SUPER,RETURN,exec,kitty
bind=SUPER,Q,killactive,
bind=SUPER,M,exit,
bind=SUPER,E,exec,nautilus
bind=SUPER,SPACE,exec,ulauncher-toggle
bind=SUPER,left,movefocus,l
bind=SUPER,right,movefocus,r
bind=SUPER,up,movefocus,u
bind=SUPER,down,movefocus,d
bind=SUPERSHIFT,S,exec,/home/christo_hartono/.bin/grimblast --cursor copy screen

bind=SUPER,1,workspace,1
bind=SUPER,2,workspace,2
bind=SUPER,3,workspace,3
bind=SUPER,4,workspace,4
bind=SUPER,5,workspace,5
bind=SUPER,6,workspace,6
bind=SUPER,7,workspace,7
bind=SUPER,8,workspace,8
bind=SUPER,9,workspace,9
bind=SUPER,0,workspace,10

bind=ALT,1,movetoworkspace,1
bind=ALT,2,movetoworkspace,2
bind=ALT,3,movetoworkspace,3
bind=ALT,4,movetoworkspace,4
bind=ALT,5,movetoworkspace,5
bind=ALT,6,movetoworkspace,6
bind=ALT,7,movetoworkspace,7
bind=ALT,8,movetoworkspace,8
bind=ALT,9,movetoworkspace,9
bind=ALT,0,movetoworkspace,10

bind=SUPER,mouse_down,workspace,e+1
bind=SUPER,mouse_up,workspace,e-1

# Startup apps
exec-once=polybar -r
exec-once=hyprpaper
exec-once=ulauncher
exec-once=/usr/libexec/polkit-gnome-authentication-agent-1

#window rules
windowrule=size 44% 60%,ulauncher
windowrule=center,ulauncher
windowrule=noblur,ulauncher

